#pragma once
// The perspective projection matrix generated by CGLM will use the OpenGL depth range of -1.0 to 1.0 by default.
// We need to configure it to use the Vulkan range of 0.0 to 1.0 using the CGLM_FORCE_DEPTH_ZERO_TO_ONE definition.
#define CGLM_FORCE_DEPTH_ZERO_TO_ONE
#include "cglm/cglm.h"

typedef struct
{
    vec3 pos;
    vec3 color;
    vec3 normal;
    vec2 texCoord;
    vec4 tangent;
} Vertex;

typedef struct {
    mat4 model;
    mat4 view;
    mat4 proj;
    vec4 lightPos;
} UniformBufferObject;

typedef struct {
    vec2 fbSize;
    float time;
} PostProcUBO;
